Repository dd3tech/bui-docs, pull requests merged in 2023-03, with the labels that each got.

#1 fix: replace gitlab logos for github
  public/github-mark-white.svg
  public/github-mark.svg
  src/components/Layout/Navbar.tsx
  src/components/TestimonialsBanner.tsx
  src/utils/constants.ts
  src/utils/index.ts
  src/utils/redirect.ts
Labels: bug

#2 ci: add workflows to github actions
  .github/workflows/build.yml
  .github/workflows/format.yml
  .github/workflows/sonarcloud.yml
  .gitlab-ci.yml
Labels: enhancement

#3 fix: cards titles and icons on FeaturesSections and ShipProject
  src/components/FeaturesSection.tsx
  src/components/StartNowSection.tsx
Labels: bug

#5 [add] component mapping and set main paragraph elements
  .github/workflows/sonarcloud.yml
  docs/buttons/button.mdx
  sonar-project.properties
  src/components/WindowEditor.tsx
  src/modules/landing/WindowEditorSection.tsx
  src/pages/docs/[folder]/[slug].tsx
  src/utils/getComponents.tsx
  src/utils/index.ts
Labels: enhancement

#11 Feat: docs layout
  docs/buttons/button-group.mdx
  docs/buttons/button-radio-group.mdx
  docs/buttons/button-shape.mdx
  docs/buttons/button.mdx
  docs/form/select.mdx
  docs/layout/card-download.mdx
  docs/layout/card.mdx
  docs/layout/container.mdx
  docs/layout/divider.mdx
  docs/layout/flex.mdx
  docs/layout/order.mdx
  docs/layout/overflow.mdx
  docs/layout/row.mdx
  docs/layout/sidebar.mdx
  docs/layout/wrapper.mdx
  package-lock.json
  package.json
  src/components/ContainerComponentDoc.tsx
  src/components/Layout/SideBar.tsx
Labels: documentation

#14 Feat(Search): implement Algolia autocomplete
  package-lock.json
  package.json
  src/components/Layout/Navbar.tsx
  src/components/Layout/Search.tsx
  src/pages/api/hello.ts
  src/pages/api/search-components.ts
  src/utils/readFile.ts
Labels: enhancement

#15 fix&feat&ref: some details
  docs/get-started/getting-started.mdx
  next-i18next.config.js
  package-lock.json
  package.json
  public/javascript-logo.svg
  public/typescript.svg
  src/components/CustomSwitch.tsx
  src/components/Layout/Navbar.tsx
  src/components/Layout/Search.tsx
  src/components/Layout/SideBar.tsx
  src/components/Switch.tsx
  src/components/WindowEditor.tsx
  src/components/index.ts
  src/hooks/useCopy.ts
  src/locales/es/common.json
  src/modules/landing/ComponentsSection.tsx
  src/modules/landing/DropdownExample.tsx
  src/modules/landing/FeaturesSection.tsx
  src/modules/landing/StartNowSection.tsx
  src/modules/landing/WindowEditorSection.tsx
  src/pages/_app.tsx
Labels: bug, enhancement
